### ISSUE TITLE
Doesn't work in webpack

### ISSUE THREAD

**Issue by chrisquinnr** [ZeroIndexPodcast/about#1]
I tried installing this in single page app using ReactifyFace and WebSmack but it doesn't work, pls halp

**Comment by jim-at-jibba** [comment]
figure it out yourself! You 🤡

**Comment by chrisquinnr** [comment]
Ok I reinstalled OSx on my tablet and now I have a service pak update??? If I remove sudo, does this help?

Code sample`;

`import { module } from 'c:\CHRIS\SITES\OPEN\DIR\%\BLOOP`
